version: '{build}'
clone_depth: 1
stack: node 8

image:
  - Visual Studio 2019
  - Ubuntu

branches:
  only:
    - master
    - dev

configuration:
  - Release

init:
  - git config --global core.autocrlf true

before_build:
  - ps: node --version
  - ps: npm --version
  - ps: dotnet --info
  - ps: "Get-ChildItem Env:"
  - ps: ./init_solution.ps1

build_script:
  - ps: dotnet build ./src/OneDas.Core/OneDas.Core.csproj                         -c $Env:CONFIGURATION /p:Build=$Env:APPVEYOR_BUILD_NUMBER /p:IsFinalBuild=$Env:APPVEYOR_REPO_TAG
  - ps: dotnet build ./src/OneDas.Hdf.Types/OneDas.Hdf.Types.csproj               -c $Env:CONFIGURATION /p:Build=$Env:APPVEYOR_BUILD_NUMBER /p:IsFinalBuild=$Env:APPVEYOR_REPO_TAG
  - ps: dotnet build ./src/OneDas.Hdf.Convert/OneDas.Hdf.Convert.csproj           -c $Env:CONFIGURATION /p:Build=$Env:APPVEYOR_BUILD_NUMBER /p:IsFinalBuild=$Env:APPVEYOR_REPO_TAG
  - ps: dotnet build ./samples/DataGatewaySample/DataGatewaySample.csproj         -c $Env:CONFIGURATION /p:Build=$Env:APPVEYOR_BUILD_NUMBER /p:IsFinalBuild=$Env:APPVEYOR_REPO_TAG

  - ps: dotnet pack  ./src/OneDas.Core.WebServer/OneDas.Core.WebServer.csproj     -c $Env:CONFIGURATION /p:Build=$Env:APPVEYOR_BUILD_NUMBER /p:IsFinalBuild=$Env:APPVEYOR_REPO_TAG
  - ps: dotnet pack  ./src/OneDas.Hdf.Explorer/OneDas.Hdf.Explorer.csproj         -c $Env:CONFIGURATION /p:Build=$Env:APPVEYOR_BUILD_NUMBER /p:IsFinalBuild=$Env:APPVEYOR_REPO_TAG

  - ps: dotnet build ./extensions/OneDas.Extension.Can/OneDas.Extension.Can.csproj                   -c $Env:CONFIGURATION /p:Build=$Env:APPVEYOR_BUILD_NUMBER /p:IsFinalBuild=$Env:APPVEYOR_REPO_TAG
  - ps: dotnet build ./extensions/OneDas.Extension.Csv/OneDas.Extension.Csv.csproj                   -c $Env:CONFIGURATION /p:Build=$Env:APPVEYOR_BUILD_NUMBER /p:IsFinalBuild=$Env:APPVEYOR_REPO_TAG
  - ps: dotnet build ./extensions/OneDas.Extension.Ethercat/OneDas.Extension.Ethercat.csproj         -c $Env:CONFIGURATION /p:Build=$Env:APPVEYOR_BUILD_NUMBER /p:IsFinalBuild=$Env:APPVEYOR_REPO_TAG
  - ps: dotnet build ./extensions/OneDas.Extension.Famos/OneDas.Extension.Famos.csproj               -c $Env:CONFIGURATION /p:Build=$Env:APPVEYOR_BUILD_NUMBER /p:IsFinalBuild=$Env:APPVEYOR_REPO_TAG
  - ps: dotnet build ./extensions/OneDas.Extension.Hdf/OneDas.Extension.Hdf.csproj                   -c $Env:CONFIGURATION /p:Build=$Env:APPVEYOR_BUILD_NUMBER /p:IsFinalBuild=$Env:APPVEYOR_REPO_TAG
  - ps: dotnet build ./extensions/OneDas.Extension.Mat73/OneDas.Extension.Mat73.csproj               -c $Env:CONFIGURATION /p:Build=$Env:APPVEYOR_BUILD_NUMBER /p:IsFinalBuild=$Env:APPVEYOR_REPO_TAG
  - ps: dotnet build ./extensions/OneDas.Extension.Modbus/OneDas.Extension.Modbus.csproj             -c $Env:CONFIGURATION /p:Build=$Env:APPVEYOR_BUILD_NUMBER /p:IsFinalBuild=$Env:APPVEYOR_REPO_TAG
  - ps: dotnet build ./extensions/OneDas.Extension.OpcUa/OneDas.Extension.OpcUa.csproj               -c $Env:CONFIGURATION /p:Build=$Env:APPVEYOR_BUILD_NUMBER /p:IsFinalBuild=$Env:APPVEYOR_REPO_TAG
  - ps: dotnet build ./extensions/OneDas.Extension.RaspberryPi/OneDas.Extension.RaspberryPi.csproj   -c $Env:CONFIGURATION /p:Build=$Env:APPVEYOR_BUILD_NUMBER /p:IsFinalBuild=$Env:APPVEYOR_REPO_TAG
  - ps: dotnet build ./extensions/OneDas.Extension.Udp/OneDas.Extension.Udp.csproj                   -c $Env:CONFIGURATION /p:Build=$Env:APPVEYOR_BUILD_NUMBER /p:IsFinalBuild=$Env:APPVEYOR_REPO_TAG

  - ps: if ($isWindows) { dotnet publish .\src\OneDas.Core.WebServer\OneDas.Core.WebServer.csproj -c $Env:CONFIGURATION /p:Build=$Env:APPVEYOR_BUILD_NUMBER /p:IsFinalBuild=$Env:APPVEYOR_REPO_TAG /p:RuntimeIdentifier=win10-x64 /p:BuildProjectReferences=false }
  - ps: if ($isWindows) { dotnet publish .\src\OneDas.Hdf.Explorer\OneDas.Hdf.Explorer.csproj     -c $Env:CONFIGURATION /p:Build=$Env:APPVEYOR_BUILD_NUMBER /p:IsFinalBuild=$Env:APPVEYOR_REPO_TAG /p:RuntimeIdentifier=win10-x64 /p:BuildProjectReferences=false }

  - ps: if ($isWindows) { msbuild .\src\OneDas.Core.Deployment\OneDas.Core.Deployment.wixproj     /p:Configuraton=$Env:CONFIGURATION /p:Build=$Env:APPVEYOR_BUILD_NUMBER /p:IsFinalBuild=$Env:APPVEYOR_REPO_TAG }
  - ps: if ($isWindows) { msbuild .\src\OneDas.Hdf.Deployment\OneDas.Hdf.Deployment.wixproj       /p:Configuraton=$Env:CONFIGURATION /p:Build=$Env:APPVEYOR_BUILD_NUMBER /p:IsFinalBuild=$Env:APPVEYOR_REPO_TAG }

test_script:
  - ps: dotnet test ./tests/OneDas.Core.Tests -c $Env:CONFIGURATION /p:BuildProjectReferences=false

artifacts:
  - path: ./artifacts/packages/**/*.nupkg
  - path: ./artifacts/msi/**/*.msi

deploy:

# MyGet (dev)
  - provider: NuGet
    server: https://www.myget.org/F/onedas/api/v2/package
    api_key:
      secure: DVadlPknnKPMR4F2+3VqeU7BFFmtLcXDHzkySA590MqQNIdzbx8HRuaPwDVbHRqX
    skip_symbols: true
    artifact: /.*\.nupkg/
    on:
      branch: dev
      CI_WINDOWS: true

# NuGet (master)
  - provider: NuGet
    server: https://www.nuget.org/api/v2/package
    api_key:
      secure: WqZcnRwOmzIa+INti/HnihBrUz0u71rTRNElX/2wbuAIbzMX6SV8h4OxJtCaX2vN
    skip_symbols: true
    artifact: /.*\.nupkg/ 
    on:
      branch: master
      CI_WINDOWS: true
      APPVEYOR_REPO_TAG: true

# GitHub (master)
  - provider: GitHub
    force_update: true
    auth_token:
      secure: Ssl8rHF6345+qU9lhUQlHRx0Ta4e6UXIQM3SEpDpjR4+WcpMJM3TvQ5gUWjwf6jQ
    artifact: /.*\.msi/
    on:
      CI_WINDOWS: true
      APPVEYOR_REPO_TAG: true